development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Postcards from Wherever
  admin_email: fredhersch@gmail.com
  
test:
    site_url: http://173.45.229.127
    site_name: Postcards from Wherever
    admin_email: fredhersch@gmail.com

staging:
  site_url: http://173.45.229.127
  site_name: Postcards from Wherever
  admin_email: fredhersch@gmail.com 
  
production:
  site_url: http://173.45.229.127
  site_name: Postcards from Wherever
  admin_email: fredhersch@gmail.com
